### ISSUE TITLE
UI scaling for 1080p displays

### ISSUE THREAD

**Issue by mbelouso** [cramerlab/warp#1]
Hey,

We only have 1080p displays and the UI cuts things off. I think some UI scaling to smaller displays could be helpful, as at 1080p the lower portion of the left hand panel is cutoff and I cannot see the options under 'Output'.
![warp-1080p](https://user-images.githubusercontent.com/25786108/43239339-3110096a-90d5-11e8-9ab6-6185644eebb8.jpg)

**Comment by dtegunov** [comment]
I'll add a scroll bar in the next point release, which will take a couple more days. I'm afraid I don't have a good workaround for this in the meantime. You're only missing 2 checkboxes: 'deconvolved average' and 'aligned stack' – both are rather unpopular in our lab.

**Comment by dtegunov** [comment]
Here is a quick fix: https://www.dropbox.com/sh/4972gzv5lmxq95f/AADbrUNbiyIeKjCz_XV54CGKa?dl=0
Just copy the files into your Warp installation folder, overwriting the existing ones.

**Comment by mbelouso** [comment]
No stress mate, I just thought to give it as a suggestion. No rush here :)
