### ISSUE TITLE
Automatic unselection of loaded files

### ISSUE THREAD

**Issue by neumann-emmanuelle** [cramerlab/warp#31]
Dear all,

I desperately try to start to analyze my tomography cryo-EM data with Warp collected a few months ago on a Krios in Heidelberg.
When I go through the first step, i.e I want to import my data, I correctely enter the path of my files (I am able to see the right number of files to import, through the wheel of the « Processing Status »). But unfortunately, all files deselect by themselves!!

We noticed that in all  .xml files generated, the answer to UnselectManual is TRUE. If we change this answer to FALSE , the file is selected and can be processed. 7,171 files have to be processed so how can we fix this problem for all the 7,171 files and why it is so? Do I need to « pre-process » my data before by changing/modifying any subtil parameters?

**Comment by psimpsonImperial** [comment]
Hi Emmanuelle... did you get to the bottom of this problem, only I see the same thing here at Imperial College London.  Select data folder in WarpM, start processing and eer images are automatically deselected during processing?

regards
Paul simpson CBEM DoLS ICL

**Comment by neumann-emmanuelle** [comment]
Hi Paul,

we managed to fix this problem by reinstalling WarpM.

Hope it will solve the problem for you also...

Best regards,

Emmanuelle
