### ISSUE TITLE
Reproducible crash due to lack of memory after retraining

### ISSUE THREAD

**Issue by bbarad** [cramerlab/warp#6]
After picking particles and retraining boxnet with them, the GPU memory does not appear to become available again and warp crashes when processing is started due to lack of memory. Quitting and reloading the software resolves this until retraining is done again.

Version is 1.0.7 beta 2.

**Comment by bbarad** [comment]
I should have mentioned - v1.0.7b2

**Comment by dtegunov** [comment]
Thanks for reporting! Google changed that part of TensorFlow in 1.10 and I didn't notice. Let's try beta 3: http://deployment.warpem.com/Warp_1.0.7beta3.msi

**Comment by bbarad** [comment]
This update resolves this issue.
