### ISSUE TITLE
How full is warp's RESTful API?

### ISSUE THREAD

**Issue by pconesa** [cramerlab/warp#8]
Hi Dmitry, I learned today about this, and the code seems very little, but it might do many things. 

Could we launch a single method combining setting + launching api methods?

**Comment by pconesa** [comment]
@dtegunov, any comment?

**Comment by dtegunov** [comment]
Hi Pablo,

the API has been introduced following a request from Ben Barad, and is very rudimentary at this point. Glad to hear there might be more interest! Let me know if you have suggestions for further methods, and I'll see if they can be implemented in the near future.

Not sure I understand the "setting + launching in one method" idea. Do you mean introducing an API method that combines LoadSettings and StartProcessing? Why would that be more useful than calling the two methods sequentially with a short delay inbetween?

**Comment by pconesa** [comment]
Thanks, @dtegunov , my question is probably misleading you. I've got no idea how to use the api. Mi intention is to be able to run warp's nice methods through the API. If just calling Starprocessing will make it, it's ok.

As you might guess, the idea would be to run warp methods from a linux box, somehow sharing the filesystem...it might impact performance, but it will be better than nothing.

**Comment by pconesa** [comment]
Hi @dtegunov I now had the chance to play with the API. It worked from the same windows box.

Next stage is to call it from  a linux box!! 

I'm bad a windows, do you know if those WS setup commands 

´´´´
netsh http add iplisten 0.0.0.0:PORT
netsh http add urlacl url=http://+:PORT/Warp user="DOMAIN\Domain Users"

´´´´

Will expose the WS to other network machines? I need to check with network admins but I'd like to be sure that windows will allow it. Maybe I need to play with windows firewall settings?

**Comment by pconesa** [comment]
In my case, I just had to expose the port in the firewall. That worked.
